runtime: python
env: flex 
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"

env_variables:
  CLOUD_STORAGE_BUCKET: qwiklabs-gcp-04-36e729238f49

manual_scaling:
  instances: 1
